### ISSUE TITLE
Missing the class HttpRequestSender in CloudService.cs

### ISSUE THREAD

**Issue by lyling** [JuniperPhoton/MyerSplash#1]

**Comment by JuniperPhoton** [comment]
To compile the project, you need to include another lib of [this](https://github.com/JuniperPhoton/JP.Utils.UWP).

**Comment by lyling** [comment]
I have complied it successfully but still miss the class.

**Comment by JuniperPhoton** [comment]
You should check that whether the lib mentioned above is included.

**Comment by lyling** [comment]
where is HttpRequestSender from ?  
I can`t find any HttpRequestSender in both git projects(this and JP.Utils.UWP) .

**Comment by JuniperPhoton** [comment]
Sorry, I forget to commit new changes to JP.Utils.UWP. Now you should Pull and get the newest.

**Comment by lyling** [comment]
This class is fine, but the ApiInformationHelper maybe another missing.

**Comment by JuniperPhoton** [comment]
Please change it to `APIInfoHelper` class, and update the `JP.Utils.UWP`. I will consider publishing `JP.Utils.UWP` to nuget so you don't have to compile the `JP.Utils.UWP`.
